### PR TITLE
Maaz

### LINKED ISSUE #2: input_lifts
void
int
Prompts user to enter the number of lifts in the building
1

### LINKED ISSUE #3: moving_lift_down
Elevator [], int index
void
Change Elevator Direction to down
1

### PR DESCRIPTION
**Pull request by MaazJamal**
This commit fixes issues with the structure definitions and defines the function moving_lift_down() and input_lifts.

### CODE REVIEW

**Review by Hariprasadm1408 — APPROVED** [review]
Looks fine for me.

**Review by divyalakshmi-padmanaban — APPROVED** [review]
Looks fine for me

**Review by ritika2 — COMMENTED** [review]
I have mentioned few points below which I consider needs to be taken care of.
For input_lifts.c file
In @brief , could you please make a correction like - if the lift count is less than 1 or greater than 100, then the function displays an error message.
In the comment after printing the input, the word "anything" is not spelled properly. Also, please correct the sentence, "clear from the stdin buffer".
In print statement of result==0, can you remove the non-integer part from the statement as 0 is also an integer, instead we can just print Enter a valid integer between 1 and 100.

For moving_lift_down.h file
In brief, can you make a correction, "declaration for the function" by removing the structure word. Also, "the function's definition is found" needs to be properly written.

For input_lifts.h file
Can you add @file and @brief in the comments.

**Review by ritika2 — APPROVED** [review]

**Comment by MaazJamal** [comment]
> I have mentioned few points below which I consider needs to be taken care of.
> For input_lifts.c file
> In @brief , could you please make a correction like - if the lift count is less than 1 or greater than 100, then the function displays an error message.
> In the comment after printing the input, the word "anything" is not spelled properly. Also, please correct the sentence, "clear from the stdin buffer".
> In print statement of result==0, can you remove the non-integer part from the statement as 0 is also an integer, instead we can just print Enter a valid integer between 1 and 100.
> 
> For moving_lift_down.h file
> In brief, can you make a correction, "declaration for the function" by removing the structure word. Also, "the function's definition is found" needs to be properly written.
> 
> For input_lifts.h file
> Can you add @file and @brief in the comments.

will include these changes in my next commit

**Pull request merged**
