### PR TITLE
Maaz

### PR DESCRIPTION
**Pull request by MaazJamal**
This commit creates the static_simulation function that handles the first part of the project. Please check for any errors.

### CODE REVIEW

**Review by Hariprasadm1408 — APPROVED** [review]
Looks good

**Review by divyalakshmi-padmanaban — APPROVED** [review]
Looks good

**Review by ritika2 — APPROVED** [review]
The code looks fine.

**Comment by ritika2** [comment]
The data folder is not there. could you please create and fix it.

**Comment by MaazJamal** [comment]
added the data/input.txt

**Pull request merged**
