### PR TITLE
Added cli_update, tests, dynamic update timer

### LINKED ISSUE #6: cli_update
Elevator[]
void
Displays elevator information on the screen
2
Maaz

### PR DESCRIPTION
**Pull request by MaazJamal**
added cli_update, tests for cli_update, 
The dynamic loop now waits for atleast 1 second.  The cli_updates has been added to the dynamic release
closes #6

### CODE REVIEW

**Review by ritika2 — COMMENTED** [review]
in cli_update.c file, the comment section is not proper as it doesn't include @file, @author , @brief, @detail
in dynamic_simulation.c file, you have mentioned static simulation in brief. Also, in return, spellings of successfull is wrong
in main file, you have mentioned in the comments that the function returns 0 for successfull completion but in function you are returning 1.
Could you please work on these one.

**Comment by MaazJamal** [comment]
> in cli_update.c file, the comment section is not proper as it doesn't include @file, @author , @brief, @detail
> in dynamic_simulation.c file, you have mentioned static simulation in brief. Also, in return, spellings of successfull is wrong
> in main file, you have mentioned in the comments that the function returns 0 for successfull completion but in function you are returning 1.
> Could you please work on these one.

Noted will do that. Thanks for pointing out.

**Review by divyalakshmi-padmanaban — APPROVED** [review]
seems perfect!

**Review by Hariprasadm1408 — APPROVED** [review]

**Review by ritika2 — COMMENTED** [review]
Could you please fix main.c file also as per my previous comments. Also, the spelling mistake in dynamic_simulation.c file.

**Comment by MaazJamal** [comment]
> Could you please fix main.c file also as per my previous comments. Also, the spelling mistake in dynamic_simulation.c file.

fixed.

**Review by ritika2 — APPROVED** [review]
Looks good now

**Pull request merged**
