### PR TITLE
tested and fixed remove_passegner_queue add_requrest_queue passenger_…

### LINKED ISSUE #4: passengers_take_in
int
Elevator[] 
Taking in passengers at elevator 
1
Maaz

### LINKED ISSUE #5: add_request_queue
Add to the passenger queue
1
Maaz

### LINKED ISSUE #7: remove_passenger_queue
int
int_array
Deleting the passenger from request queue
1
Maaz

### PR DESCRIPTION
**Pull request by MaazJamal**
…take_in

I have tested and fixed the bugs in remove_passenger_queue add_request_queue and passenger_take_in
I have also made changes as recommended by riktika on previous commit.

closing

### CODE REVIEW

**Review by Hariprasadm1408 — APPROVED** [review]
Looks good to me

**Comment by ritika2** [comment]
Looks fine to me

**Review by ritika2 — APPROVED** [review]

**Comment by divyalakshmi-padmanaban** [comment]
Looks fine to me

**Review by divyalakshmi-padmanaban — APPROVED** [review]
Look good

**Pull request merged**
